package com.embl.techtest.entity;

import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.builder.ToStringBuilder;

import javax.persistence.*;

@Entity
@Table(name = "persons")
public class Person {

    @ApiModelProperty(notes = "Database Autogenerated Person ID")
    private long id;

    @ApiModelProperty(notes = "First Name of the Person")
    private String first_name;

    @ApiModelProperty(notes = "Last Name of the Person")
    private String last_name;

    @ApiModelProperty(notes = "Age of the Person")
    private int age;

    @ApiModelProperty(notes = "Person's Favourite Colour")
    private String favourite_colour;

    public Person() {
    }

    public Person(long id, String first_name, String last_name, int age, String favourite_colour) {
        this.id = id;
        this.first_name = first_name;
        this.last_name = last_name;
        this.age = age;
        this.favourite_colour = favourite_colour;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    @Column(name = "first_name", nullable = false)
    public String getFirst_name() {
        return first_name;
    }

    public void setFirst_name(String firstName) {
        this.first_name = firstName;
    }

    @Column(name = "last_name", nullable = false)
    public String getLast_name() {
        return last_name;
    }

    public void setLast_name(String lastName) {
        this.last_name = lastName;
    }

    @Column(name = "age", nullable = false)
    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    @Column(name = "favourite_colour", nullable = false)
    public String getFavourite_colour() {
        return favourite_colour;
    }

    public void setFavourite_colour(String favoriteColour) {
        this.favourite_colour = favoriteColour;
    }

    @Override
    public String toString() {
        return new ToStringBuilder(this).append("firstName", first_name)
                .append("lastName", last_name)
                .append("age", age)
                .append("favouriteColour", favourite_colour)
                .toString();
    }
}
